<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="GUR-BXTI-L162" name="channelnewsasia.com.Scenario1" tests="3" failures="1" timestamp="25 Aug 2021 05:01:28 GMT" time="31.173" errors="0">
  <testcase name="Scenario2method" time="31.173" classname="channelnewsasia.com.Scenario1">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Ensure headlines are expected expected [111 new locally transmitted COVID-19 cases in Singapore, including 24 linked to dormitory in Woodlands] but found [Singapore&#039;s Yip Pin Xiu advances to women&#039;s 100m backstroke S2 final at Tokyo Paralympics]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Ensure headlines are expected expected [111 new locally transmitted COVID-19 cases in Singapore, including 24 linked to dormitory in Woodlands] but found [Singapore's Yip Pin Xiu advances to women's 100m backstroke S2 final at Tokyo Paralympics]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at channelnewsasia.com.Scenario1.Scenario2method(Scenario1.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Scenario2method -->
  <testcase name="fetchWeather" classname="channelnewsasia.com.Scenario1">
    <skipped/>
  </testcase> <!-- fetchWeather -->
  <testcase name="Scenario1method" classname="channelnewsasia.com.Scenario1">
    <skipped/>
  </testcase> <!-- Scenario1method -->
</testsuite> <!-- channelnewsasia.com.Scenario1 -->
